---
- name: Install and Proxmox
  hosts: pve
  become: true
  roles:
    - ansible_user
    - pve_updates
    - pve_disable_nag
    - pve_network
    - pve_cluster
    - pve_ceph
    - pve_dns01_route53
