name: Ansible CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install yamllint
        run: pip install yamllint

      - name: yamllint
        run: yamllint .

      - name: ansible-lint
        uses: ansible/ansible-lint@v24.6.1

      - name: markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v16

  security:
    runs-on: ubuntu-latest
    name: kics scan
    permissions:
      security-events: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Mkdir results-dir
        run: mkdir -p results-dir

      - name: Run KICS Scan with SARIF result
        uses: checkmarx/kics-github-action@v2.1.1
        with:
          path: "roles,tasks"
          fail_on: critical,high,medium
          output_path: results-dir
          platform_type: ansible
          output_formats: "json,sarif"
        continue-on-error: true
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results-dir/results.sarif
